#!/bin/bash

. /data/devhome/dev-kits/jump_config

conn=()
show=()
passwd=()
i=1
for item in "${config[@]}"; do
    conn[$i]=$(echo $item|awk '{print $1}')
    show[$i]=$(echo $item|awk -F'|' '{print $1}')
    passwd[$i]=$(echo $item|awk '{print $NF}')
    i=$(($i+1))
done

while [ "$server" != "exit" -a "$server" != "e" ]; do
    dir=$(pwd)
    is_devhome=$(pwd|grep "^\/data\/devhome"|wc -l)
    if [ $is_devhome -eq 0 ]; then
        dir="/data/devhome"
    fi
    
    echo "=========================================="
    i=1
    for item in "${show[@]}"; do
        echo "$i > ${item}"
	i=$(($i+1))
    done
    echo ""
    read -p "pelase select a server: " server

    user=$(echo ${conn[$server]}|awk -F'@' '{print $1}')
    ip=$(echo ${conn[$server]}|awk -F'@' '{print $2}')
    password=${passwd[$server]}

    case $server in
    0)
        /usr/bin/expect /data/devhome/dev-kits/dev_docker $dir
        break
        ;;
    1|2)
        dir=$(echo $dir|awk -F'data\/devhome' '{print $2}')
        /usr/bin/expect /data/devhome/dev-kits/server_conn.sh $user $ip $password "cd /data/devhome/${user}$dir"
        break
        ;;
    3|4|5|6)
	/usr/bin/expect /data/devhome/dev-kits/server_conn.sh $user $ip $password "ls"
        break
        ;;
    *)
        continue
    esac
done

